### ISSUE TITLE
Would you like to share how the graph is produced?

### ISSUE THREAD

**Issue by ngolin** [ksz-ksz/rxjs-insights#2]
Would you like to share how the graph is produced? Which package can do this? Thank you.

**Comment by jdgarvey** [comment]
Looks like these files are the implementation: https://github.com/ksz-ksz/rxjs-insights/tree/master/packages/devtools-extension/src/app/components/graph

**Comment by ksz-ksz** [comment]
Hi, it's using d3 for the layout (see https://github.com/ksz-ksz/rxjs-insights/blob/master/packages/devtools-extension/src/app/components/tree.ts), but the graph component is a custom thing, as @jdgarvey pointed out already the implementation can be found in https://github.com/ksz-ksz/rxjs-insights/tree/master/packages/devtools-extension/src/app/components/graph, with the entry point being the graph.tsx file. It's basically React + [TransitionGroup](https://reactcommunity.org/react-transition-group/transition-group) + [GSAP](https://greensock.com/gsap/).
