### ISSUE TITLE
It seems that the instrumentation was not installed

### ISSUE THREAD

**Issue by marnec-ad** [ksz-ksz/rxjs-insights#4]
Can't connect Angular project to rxjs-insights chrome plugin.

message shows up: `It seems that the instrumentation was not installed...`

I followed each step of the docs at: 
 - https://github.com/ksz-ksz/rxjs-insights/blob/master/docs/instrumentation/setup/angular.md
 - https://github.com/ksz-ksz/rxjs-insights/blob/master/docs/devtools/setup.md

Furthermore plugin docs state that `connect()` will return a `Promise<boolean>` while `connect()` signature is `Promise<void>`

specs:
- angular 14.x.x (dev server running on node 14.19)
- chrome 105 running on
- wsl2 on windows 11
- installed:
  - "@rxjs-insights/rxjs7": "0.4.3",
  - "@rxjs-insights/plugin-webpack5": "0.4.2",
  - "@angular-builders/custom-webpack": "14.0.1",
  - "@rxjs-insights/devtools": "0.4.3"

**Comment by ksz-ksz** [comment]
Hey, thanks for reaching out. I'll try to reproduce your setup and see how it goes over the weekend.
And regarding the connect function signature, you got me. I'm working on some improvements but haven't released the new packages yet. I'll do that i the upcoming week.

**Comment by ksz-ksz** [comment]
I'm sorry to say that "it works on my machine". I've created a test project that you can find here: https://github.com/ksz-ksz/rxjs-insights-angular14. You could test if it works in your setup (if it does, it must be something with the project and not the environment).
Other than that:
1. it's not stated anywhere in the [guide](https://github.com/ksz-ksz/rxjs-insights/blob/master/docs/instrumentation/setup/angular.md), but the custom webpack config is loaded only when you run `ng serve` (either directly or via script: `npm run start`, `yarn start`, etc.); make sure that you are using one of those commands,
2. the message `It seems that the instrumentation was not installed...` suggests that the plugin is not working; you could try adding a `console.log("woohoo")` at the beginning of the `development.config.js` and check the `ng serve` command line output; if the "woohoo" is not present there, it means that the custom builders did not work; if it's present, then the plugin itself fails silently for some reason,
3. it would be helpful if you'd share the `angular.json` file content (or the whole project, if you don't mind sharing it :D)

**Comment by ksz-ksz** [comment]
Stale, closing.
