### ISSUE TITLE
devtools throws 404 errors, including for '[ContextTrackerZone]'

### ISSUE THREAD

**Issue by jmcmichael** [ksz-ksz/rxjs-insights#5]
Hi, thank you for your work developing this tool, it looks like it will be extraordinarily useful. I'm having trouble configuring an app to drive the chrome plugin, and am not sure how to proceed troubleshooting.

The extension indicates that it has successfully connected with the devtools, but then immediately throws three errors, one of which appears to be thrown by the `zonejs-tracer` package. 

Specifically, immediately after the console reports `RxJS Insights: connected with the devtools.`, three 404 errors are thrown:

- `GET http://127.0.0.1:4200/[%3Croot%3E] 404 (Not Found)`
- `GET http://127.0.0.1:4200/[angular] 404 (Not Found)`
- `GET http://127.0.0.1:4200/[ContextTrackerZone] 404 (Not Found)`

[The `angular.json` file for the project](https://github.com/jmcmichael/civic-v2-dev/blob/forms-refactor--features-to-mixins--rxjs-insights-config/client/angular.json) includes updates from [the previous version](https://github.com/jmcmichael/civic-v2-dev/blob/forms-refactor--features-to-mixins/client/angular.json) that I attempted to copy as closely as I could from the one in [your `rxjs-insights-angular14` project](https://github.com/ksz-ksz/rxjs-insights-angular14/blob/master/angular.json). I don't recall having to make any major changes to get it to the point where it is currently compiling and connecting.

I did do a migration from angular v13 to v14, however the error persisted. I thought that it might be its proxy configuration which also requires `custom-webpack:dev-server`, but the error persists when I comment out its options object.

I tracked the `ContextTrackerZone` in the error message [to the `zonejs-tracer` library](https://github.com/ksz-ksz/rxjs-insights/blob/7327e0be9e7423da68deaa1581e76b7dfc456286/packages/tracer/src/lib/zonejs-tracer.ts#L20), but am stuck there as to how to identify a problem with the host app or its configuration.

Thanks again for your work on this tool, I'm looking forward to using it to troubleshoot some particularly complex observables. Here's the screenshot of the console output summarized above:

<img width="596" alt="Screen Shot 2022-09-25 at 14 27 29" src="https://user-images.githubusercontent.com/132909/192161705-93922e7e-a7b7-4310-9d75-c286a7445283.png">

**Comment by ksz-ksz** [comment]
Hey, thanks for reaching out! Is the RxJS Insights devtools panel crashing (so that it's unusable)? From the console output it seems that there's some problem with the sourcemaps (which, in theory, should be handled gracefully by the devtools).
I'll take a look at your repo to see if I can spot anything obvious.

**Comment by ksz-ksz** [comment]
I created a patch for you that is working for me (I branched from the https://github.com/jmcmichael/civic-v2-dev/tree/a2ae3c5): [rxjs-insights.zip](https://github.com/ksz-ksz/rxjs-insights/files/9649953/rxjs-insights.zip).
I did not start the server so it breaks at /api/status request, but I was able to inspect the observable created by the HttpClient and see it in the devtools panel. No console errors are present (apart from the failed request) and the sourcemaps works.
Please, check it out and let me see if it works for you. If not, I'd have other suspects (rxjs-insights and rxjs-spy might not like each other; the error-stack-trace dependency has a fixed resolution).

**Comment by jmcmichael** [comment]
Thank you so much, I will check out your patch this weekend, and let you know how it goes!

**Comment by ksz-ksz** [comment]
Stale, closing.
