### ISSUE TITLE
Angular setup not working

### ISSUE THREAD

**Issue by mangelo123** [ksz-ksz/rxjs-insights#6]
I followed the instructions for Angular and I am getting the following error for ng server:

Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(extraWebpackConfig).

**Comment by ksz-ksz** [comment]
Hey! Could you please share the repo or the angular.json contents?

**Comment by mangelo123** [comment]
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "packages",
  "projects": {
    "rework": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "packages/rework",
      "sourceRoot": "packages/rework/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist/rework-customer-portal",
            "baseHref": "/rework-customer-portal/",
            "index": "packages/rework/src/index.html",
            "main": "packages/rework/src/main.ts",
            "polyfills": "packages/rework/src/polyfills.ts",
            "tsConfig": "packages/rework/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "packages/rework/src/favicon.ico",
              "packages/rework/src/config.json",
              "packages/rework/src/assets",
              {
                "glob": "**/*",
                "input": "./node_modules/@domanirx/theme/images",
                "output": "./images/"
              }
            ],
            "styles": [
              "node_modules/@domanirx/theme/domanirx.css",
              "packages/rework/src/styles.scss"
            ],
            "scripts": [],
            "extraWebpackConfig": "packages/rework/webpack.config.js",
            "commonChunk": false
          },
          "configurations": {
            "production": {
              "sourceMap": {
                "scripts": true,
                "hidden": true
              },
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "packages/rework/src/environments/environment.ts",
                  "with": "packages/rework/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },

            "qc": {
              "fileReplacements": [
                {
                  "replace": "packages/rework/src/environments/environment.ts",
                  "with": "packages/rework/src/environments/environment.qc.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "1mb",
                  "maximumError": "2mb"
                }
              ]
            },

            "dev": {
              "fileReplacements": [
                {
                  "replace": "packages/rework/src/environments/environment.ts",
                  "with": "packages/rework/src/environments/environment.dev.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "1mb",
                  "maximumError": "2mb"
                }
              ]
            },

            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true,
              "customWebpackConfig": { "path": "development.config.js" }
            }
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "rework:build:production"
            },

            "qc": {
              "browserTarget": "rework:build:qc"
            },

            "dev": {
              "browserTarget": "rework:build:dev"
            },

            "development": {
              "browserTarget": "rework:build:development"
            }
          },
          "defaultConfiguration": "development",
          "options": {
            "port": 8003,
            "publicHost": "http://localhost:8003",
            "extraWebpackConfig": "packages/rework/webpack.config.js"
          }
        },
        "extract-i18n": {
          "builder": "ngx-build-plus:extract-i18n",
          "options": {
            "browserTarget": "rework:build"
          }
        },
        "test": {
          "builder": "ngx-build-plus:karma",
          "options": {
            "main": "packages/rework/src/test.ts",
            "polyfills": "packages/rework/src/polyfills.ts",
            "tsConfig": "packages/rework/tsconfig.spec.json",
            "karmaConfig": "packages/rework/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "packages/rework/src/favicon.ico",
              "packages/rework/src/config.json",
              "packages/rework/src/assets"
            ],
            "styles": [
              "node_modules/@domanirx/theme/domanirx.css",
              "packages/rework/src/styles.scss"
            ],
            "scripts": []
          }
        }
      }
    }
  },
  "cli": {
    "analytics": false
  }
}

**Comment by ksz-ksz** [comment]
Could you please tell what angular version are you using? It seems that your angular.json validates just fine against the [latest stable (14.2.8) schema.json](https://unpkg.com/@angular/cli@14.2.8/lib/config/schema.json) (I checked it using https://www.jsonschemavalidator.net/).

You might want to try if removing the `"$schema": "./node_modules/@angular/cli/lib/config/schema.json",` line from your angular.json will make it work (however, this would be only a workaround).
